from controller.CalculadoraController import CalculadoraController
from controller.ComboCascadaController import ComboCascadaController
from controller.ComboSimpleController import CombSimpleCascadaController
from controller.MayoryMenorController import MayoryMenorController

formulario = CalculadoraController()